[build]
  base = "/"
  publish = "frontend"
  functions = "backend"
  command = "echo 'No build step required for frontend'"

[[redirects]]
  from = "/get-data"
  to = "/.netlify/functions/get_data"
  status = 200
